apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ilvx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilvx
    app.kubernetes.io/part-of: byoc-app-ufnt
  name: ilvx
spec:
  rules:
  - host: ilvx-byoc-zogp-tenant.apps.7c195d8641b2cce96e04.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: ilvx
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
