apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ilvx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ilvx
    app.kubernetes.io/part-of: byoc-app-ufnt
  name: ilvx
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: ilvx
status:
  loadBalancer: {}
